# Generated by Django 3.2.6 on 2021-08-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210821_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateField(default='2021-08-22'),
        ),
    ]
